var idea_list = [
"Game where you are a talking cat trying to bring people together but you can only talk to any one person once.",
"You play as a single mother who accidently gets trapped inside a mech that she has been building. She must now bring up her child as a mech",
"What if you found out that every brick in your home was once a person? What if you could still talk to them? What if they had secrets?",
"Imagine a game world where every single entity looks like Ellen Page (Even chairs and trees) How would this change society?",
"I want to make a non violent war game in which you try to negotiate your way into counties to supply war victims with humanitarian aid.",
"A game that starts with one room. When your character dies the room expands revealing more environment and you are reborn.",
"I was in talks with HBO once to create a Sopranos game but they didn't like my pitch about making the entire game one long therapy session",
"Maybe one day people will put the same amount of effort they've been putting into arguing about DRM into demanding more creative games",
"Idea for fun quiz show on XboxOne. It asks what you said or did at certain times and dates. You answer and then it plays you the evidence",
"FPS where you only control left arm. Right arm has weapons and loves killing. As the left arm you must keep knocking weapons out of reach",
"Imagine if you accidentally ran over your loved one and their scream became part of the background music so you never forgot what you did?",
"Game where you play a lifeguard on an empty beach. You can create invisible victims to save as well as invisible threats such as sharks etc",
"Imagine a game where if you see your own reflection you die",
"I'll never make a racing game. Unless you race tears down a child's face to manipulate others.",
"What if there was a game where everyone in the same world were living in their own individual time?",
"Action game where talking is your weapon. Because when you talk it creates dynamic speech bubbles which can then be used as cover",
"I want to make a dancing game featuring only old people with disabilities.",
"When I run into someone in a racing game I want to know how they are. Maybe they're off to pick up their kids? Could I help them out?",
"Imagine a sports game where you control the player's family which in turn affects how the player plays on the field.",
"Game where you are riding along an endless highway with just your loved one. Filling up your car with gas makes your loved one grow older",
"Imagine playing assassin bees that sting targets in vulnerable positions. Such as flying into a car window as it turns on a mountain?",
"When you killed your loved one they turned into an angry ocean that you're forever sailing across. You must help the ocean to forgive you",
"Game in which you can give birth to a game bug and develop the bug throughout the entire game.",
"Game where as you get closer to environment the further it drifts away from you. I'm not sure what I mean but I know it's innovative.",
"Imagine a game that came with a old fashioned wrist watch and winding the hours back and fourth changes the time in the actual game?",
"Imagine being trained to be a sniffer dog, taught to track down drugs when really you just want to track down friendship and love",
"What if doing your child's homework upgraded your weapons?",
"When the Sun is up people walk to the right but you walk left. Reverses when sun is down. Cross paths to power up and gain more control",
"Imagine your only weapon being a sword but your head is a lit candle. Using the sword blows out the flame which is essentially your brain.",
"Game where you control a tunnel to connect loved ones. You progressively upgrade your tunnel to keep travelers healthy and happy",
"Hope Watch Dogs isn't all action.What if during a date you could hack the dimming lights in a restaurant to increase romance possibilities?",
"Trying to write a game where you play an alarm clock that has the power of teleportation and time travel.",
"Just imagine if all people were lenses? Looking through certain people in certain places reveal secrets within the environment.",
"Game that locates your family tree and turns them into characters for you to interact with.",
"What if a door was your companion? You can place him/her on any surface and can only interact with others on the other side of the door",
"What if you could control the amount of pixels on NPCs, take out pixels and put them elsewhere in the environment to solve puzzles?",
"I want to make one copy of a game that will be hidden deep within this Earth. Then create a kickstarter to fund a group to retrieve it.",
"Imagine having special abilities on your birthday in all games? Your car is faster, you can jump higher, you're more powerful etc",
"A game where you can only progress during 3 random minutes every day. It's up to social media to help people play at the right time",
"Game where you play a day that lasts 1 second. Need to find elements that stretch time by 1 second. You win when you live a 24 hour day.",
"Game where the left stick controls your selected character and the right stick controls the moon.",
"Imagine watching a film that can be interacted with in the theatre by smartphones. Tapping the hero makes them laugh etc. That's the future.",
"Game about an assassin trying to make a hit on a target. You control everyone else in the area, finding creative ways of keeping them apart",
"It's all in the eyes. I want to make a game where you can have instant replays showing your eyes close up during emotional scenes.",
"Imagine viewing a friend's game but really it's just a random person, would you feel betrayed? That's the idea behind my next game",
"I want to make a ps4 game that is just a room with locked door that can only be opened if 1 million users are watching you at the same time",
"Jonathan Blow has inspired me to make a game in which you are in a wonderful environment that you open up by doing crosswords.",
"5 minute game where you play an asteroid that is headed towards Earth. Everyone hates you. All you can do is talk, what would you say?",
"Game where the ability to instantly change the difficulty of the game on the fly is part of the game's core mechanic.",
"Game in which all you can do is make 1 wish. Then you just sit back and see how it changes the world and if it interacts with other wishes.",
"Game where you play as an evolving desert, creating increasingly advanced mirages to manipulate travellers that dare to set foot on you.",
"Action game where every time you die you spawn in the same area but 10 seconds in the past. You need to rescue yourself to continue.",
"If you die in my new game, an image of your death will overwrite your facebook/twitter profile pic until you get past that section",
"What if you had an ability to cast autosave on other characters? need to cast it as late as possible but not too late that they get trapped",
"What if you played as a letter of the alphabet that could jump into speech bubbles to either help people or get them into deep trouble?",
"War game where you have just one grenade. It talks to you and helps you through the tough times.",
"If you die your last body turns into a brick. You can then pick that brick up with new body and use it towards making a bridge. Repeat",
"Game where you play as youtube and become self aware. You must cleanse yourself of banal cat videos or face a life of hopeless ennui.",
"Action game where your child follows you. Must hide them when fighting and block out sounds of profanity with gunshots.",
"Imagine if every switch in your house transferred into data within a game?",
"Imagine a game where a character is unable to jump. So you instruct them to watch as you load up a platformer and jump, then they can jump.",
"World where everyone but you are deaf. You can temporarily give people the power of hearing at the right time to benefit your journey.",
"Imagine if you could control an enemy on the console game your child is playing without them knowing via a smartphone?",
"Game where you tap every second to count down to 2014. Whoever keeps it going for the longest wins something truly amazing.",
"Game where you must help a 3 year old land a crashing plane. Child will only take notice if you use puppets over a video call.",
"Puzzle Game where you fire different odors onto creatures. Other creatures interact with them differently depending on the odors.",
"Scrolling brawler where you play the enemies and have to build self esteem of weak hero by dramatically jumping through windows when hit etc",
"Game that helps you overcome phobias. Imagine augmented reality where you play with a cute spider but it progresses into a scary spider.",
"Game where the only enemy is you. You're going to jump off a cliff. Exit your body as your soul and talk your body into not jumping.",
"Cutesy platformer that turns into a violent slash em up between 11pm and 3am every night.",
"MMO where we all run on treadmills to keep the world light. When someone dies or leaves it gets darker until eventually it's unplayable",
"Game in which your only ability is to leave sticky notes in various places to manipulate people into achieving ever increasing tasks",
"I want to make Milo for the WiiU. If you switch to TV, Milo will sit down and watch the TV with you.",
"Imagine if a game's audio initially hated you, making horrible sounds but slowly it falls in love with you and plays sounds of pure bliss?",
"Game where around 1000 players need to be in the game spinning plates otherwise the game ends. How long would the game last?",
"Interesting fact, right now more people are tapping on my cube than playing Black Ops 2.",
"You are the last Bee in a world where everyone hates you. You can't sting people but can fly into car windows and cause accidents etc",
"Had an idea for a FPS where your head is a mirror. Your only weapon is to bounce sunlight in the right directions. You also control the sun.",
"If I made a COD game you would be a forgotten soldier in a cell who has to keep tapping on the door. How long would players tap for?",
"Imagine if a game was packaged with a beautiful and complex plug in lamp and the lights adjust depending what you do in the game?",
"Imagine a game that required 30 hours to get to the title sequence and you don't even get to control your character until the sequel.",
"Game where final boss walks right next to you but you're both separated by an invisible wall? By the time the wall opens you're in love.",
"Survival horror in which a family are in a pitch dark castle. You have a flashlight but if the 1 year old baby isn't holding it they cry.",
"Decided to hold back on Curiosity to avoid harming sales of Unfinished Swan, will release it around the time of AC3, Halo4 and Ops2 instead.",
"Imagine a game where you instantly die if you see yourself? The enemy is reflection.",
"Survey.What if there was a free game where your avatar is always crying. It doesn't affect the game but you could stop it for $2. Would you?",
"Imagine sharing the same character among friends but you're all in different places. Player1 punches air but hits an enemy next to Player3",
"FPS where you must hold out a bowl of hot soup and must not spill a single drop of it whilst making your way through hostile environments",
"What if you could only kill when not visible? For example you need to swing the camera so a column hides your character from you.",
"If I made a zombie game it would feature just one dangerous zombie, your child. You must sneak out avoiding society, trying to find help.",
"Imagine, playing the greatest little game of all time but every completion takes away a fun element so you're destroying the game you love",
"Social experiment. Game in which the high score is based on the distance you drop your Smart Phone without it breaking.",
"I wanted new Xbox achievements system to have no numbers. You are in a tower, every achievement opens a door. What is behind the next door?",
"Game where you must try and fall asleep by stopping all sources of potential interruption within your environment.",
"Came up with an idea with David Cage once where you control Nolan North in his personal life during a crisis where he's lost his voice.",
"I love questions that make you realize just how unexplored gaming is. For example, have you ever whispered a secret to a NPC?",
"What if we all played a creature with 1 million eyes and we each saw through our own unique eye? Working together to travel dangerous lands",
"I have an idea where you can project a game onto people's faces and the game plays differently depending on the shape of the face.",
"Have we ever truly played within a game? or have we just been giving instructions all this time? Has anyone ever REALLY played a game?",
"Game where you play an airport security person who must choose who to check and pat down without making the chosen person feel violated.",
"Game where you collect movement and sounds and then go back as a DJ and mix those visuals and sounds back into the environment to progress.",
"What if you played as a rug in the white house who is able to secretly roll around and look under doors?",
"Game in which you must reunite missing pets with their owners using your power of telepathy. You can see through the pet's eyes.",
"Platformer where if you fall in a pit you're trapped forever unless you can emotionally manipulate nearby enemies to pull you back up.",
"Game where score is based on how loved you are in a old folks home. Must sneakily murder other folk's loved ones so you get the most love.",
"Game where you can only ever fire 1 bullet. Then the game is slowed down and you direct/maintain it through the entire game with powerups",
"Game where you are a devastating bomb, you don't know where you are or who planted you.",
"I want to make a game that a parent plays during labor. The final boss can only be truly defeated by the sound of a crying baby.",
"How about a game where you control the UI to fool the NPC hero? Slyly adjusting stats when they are busy to adjust their mood appropriately.",
"When I first saw Street Fighter I was disappointed. I was hoping that you could build up your own street and fight other streets.",
"We as an industry are too obsessed with realism. i.e Why would designers never dare to make a character with a supermarket for an arm?",
"Game in which you play a superhero but every time you use your powers you gradually gain weight.",
"If you were to ask me to rate how life changing the content of the cube is I would say 100 out of 100, maybe for some 99 but for most 100",
"What is inside the cube is far more interesting than what is on Mars, that's why I'm not even thinking about suing NASA over copyright.",
"Imagine a game where the only way to destroy the family boss is if everyone in your family tree that is still alive is cheering you on?",
"Imagine an entire game set in a traffic jam where you fall in love with the driver next to you. You help each other get through the jam.",
"Survival horror based in a huge bouncy castle, all you have is a needle gun and duct tape.",
"My new kickstarter will be a MMO set in a polluted world. If you fund us $10,000 you will get a gas mask and can go outside.",
"Enemy with blue spike above them. To kill them you need to go back in time when they were a child and force them to jump when they see blue",
"Imagine a game where I hide within a huge virtual world. If any of you find me within a year you will become a director of our studio",
"I want to make a Batman game where you play as Alfred, trying to protect Bruce Wayne from hurting himself by knocking down his confidence.",
"Game in which you have to be the only person on the server and play for over 4 minutes and 32 seconds to win.",
"Survival horror should not have magic inventory. You should pay poor people to travel with you carrying your inventory instead.",
"I want to write a book and somewhere will be a clue on how to open a door in a game that I make in 20 years from now",
"A racing game based in areas filled with people, you can rewind to avoid hitting them but every rewind makes your car faster.",
"Game where you always drip paint. During the last act you discover that you've been painting the final boss, can you destroy your own art?",
"Thinking of starting a kickstarter to raise $50,000 so that I can buy the diamond pick axe in 'Curiosity' and then refuse to use it.",
"Imagine being 5 years old playing out a scene in a game. The game shuts down for 50 years, you then team up with your 5 year old self to win",
"You know, I have urges to do a twist on the pet sim genre where you play the pet and must cuddle your owner when they are sick or depressed",
"Imagine a game where people throw money into fountains. Now what if I told you that not only can you see their wishes but steal them too?",
"You are a sad lonely firework in a dusty shed on 4th July, what if you could use ghosts to sneak you into big display in New York?",
"You play a disco ball. You can roll and attach to anything. Collect new songs to activate, each having unique effect on the world around you",
"A village with just 2 houses. You control a doorbell for both houses. Can you bring the 2 inhabitants together and make them fall in love?",
"If I remade Tombraider I'd make you play as Lara's butler, then you can just enjoy exploring and getting treasure without abuse from locals",
"Soccer game where you feel guilty. Every kick of the ball results in visions of your fans beating up innocent people and destroying property",
"It's fascinating isn't it? Put a player in an empty room with a grenade they will eventually throw it rather than turn off the game. Why?",
"You play a sad and doomed elephant who is constantly blowing water out of it's trunk and flooding environments and their inhabitants",
"Couldn't sleep last night, was constantly trying to remember ANY game where the main enemy of the game is seen crying?",
"Why do keys remain in your inventory until you use them? What if you could actually misplace them? or you unknowingly dropped one?",
"You know how some people capture a fish and let it go? but what if you replaced fish with towns people.",
"What if each tap of the cube cost $10 and the person who paid $77k for the super chisel found $100k+ inside made from other peoples taps?",
"What if the content of the cube made you the very first god in my upcoming MMO? #whatsinthecube",
"Well, I know what's in the middle of the cube. And whoever breaks in there, I promise you this, it is the most amazing thing #whatsinthecube",
"How about an escort mission where YOU play as the escort for a horrible agent. Give them a mental breakdown by repeatably getting in the way",
"Idea for WatchDogs game. What if you could hack a electronic road sign to say 'I love you' as you're driving past it with your loved one?",
"Imagine wanting to keep killing yourself just to get to a checkpoint where you can spend more time with your loved one before they died",
"New Prince of Persia game where you control someone who only has legs when he dreams #E3wish",
"Imagine playing a game and from your kitchen it hears someone saying 'peanuts' and then peanuts start falling into the game and can be used",
"EVERY game released so far can be broken down to basically be Snakes and Ladders but what if a game had no snakes or indeed ladders?",
"A game that is constantly interrupted by 10 adverts. For every 100 enemies you kill one random advert will never play again.",
"What if your reward was another player's profile? What if they were ALSO looking for love and so you meet. Imagine that for a moment",
"I'd like to see a war game in which you come in after the war to clean up debris, as you do you see ghosts of those fighting around you",
"Imagine a game that's controlled by a actual baby's sound waves? As your baby's vocabulary grows so does your avatar's range of abilities",
"What if to create a save point you had to give birth to it? What if the save point followed you but could easily get upset and run away?",
"I am officially declaring this Friday NGPD 'No Game Pad Day',  let's show the industry that we're bored of using them. #nogamepads",
"Imagine a sim where you work in a factory that manufactures weapons but your're forced to watch how every weapon is eventually used.",
"So Edge gave Max Payne 3 a 7 which means it's a failure. See, people are finally getting tired of games with guns. Let's move on shall we?",
"You live in a see through house, your family is replicated from the future on the left and from the past on the right. Interaction is vital",
"Imagine if going through a door resolved in coming out the first door of the game but with the same object you carried through the last door",
"I remember opening minds by showing same sex marriage in Fable 2, some people laughed but now even Obama has played it and changed his mind",
"What if you could paint a gun onto a wall then change the perspective so that it's aimed at an enemy?",
"Imagine creating a virtual habitat for a friend. You could write something under their carpets, will they ever pull them up to see?",
"Playing Trials. This may sound strange but in the future will we will be playing against 'ghosts' of people we know who have passed away?",
"One day there will be a game where you feel so much remorse after killing someone that you will vow never to play a videogame ever again.",
"Imagine a world with just one flower where you spend the duration of the game interacting with people in order to decide who to give it to",
"A survival horror where your only weapon is pizza? when you run out you have to call up pizza delivery with an address then wait and survive",
"What if in the future they gave an Oscar to the player who manages to pull off the best emotive performance in a video game?",
"Left eye sees environment one way and right eye sees it another way. Here's the thing, what if you could control individual eyelids?",
"You are in a empty blank room. Now imagine if when you closed your eyes you saw another world? Yet you can only breathe when eyes are open",
"Next Medal of Honor to feature a wife? Imagine a game where you play a wife spy and get distracted by husband's phonecalls from the war?",
"I want to make a game in which we all die from a early disaster yet our children will pay respect 50 years later within the same game",
"What if there was a FPS in which you are invisible apart from your gun which you have to keep hiding within the environment?",
"I would love to recreate the E.T game where we each control a hole in a MMO environment. You get XP and love if he falls down your hole.",
"Game in which you paint your feelings onto a canvas using a guitar controller",
"Imagine if there was a beta where we all controlled 1 pixel and came together to create a world for my next game?",
"Game in which you control curtains, closing yourself depresses inhabitants where as opening up makes them happier.",
"My new game will be called #5xiOg490xxoSS5io2.5",
"Imagine a game in which you fight in order to stop it turning into a cinematic game",
"Imagine if X could only move within paintings in a gallery? you also control Y who must place the correct paintings to allow X to transition",
"What if you actually controlled a heart? it must be a sad life. Never seeing the person who you're giving life to?",
"Game in which you transfer from body to body of people stuck in lifts all over the world, forever in time.",
"Imagine, you play a baby in a pram and can only see your parent's faces.  Studying those faces deeply is the key to true progress",
"Also in my new kart game racing against ghosts isn't a gimmick, it's an integral part of the story",
"Just imagine a kart game where you spend most of the game building one with your mother in a shed, you are the only people alive on earth",
"Game in which you can only progress during one minute silences. You need to find creative ways to keep the nation having 1 minute silences.",
"What if sound effects were people that traveled the world searching for the right song to fall into? What if that song changed someone?",
"Game in which you create the end cinematic. Then you work your way from the start of the game to make a perfect connection into that ending.",
"Just dropped rice on the floor, am sure there is a game idea here somewhere. pic.twitter.com/fu0ZQNTQ",
"FPS War game, you control the teddy bear of a child who has just escaped a death camp. Help them find their mother using your wits",
"If anyone ever wanted to base a serious gamejam on my world changing designs I would give it my blessing and support. There you go.",
"Game where you control a full stop. Enemies read you stories you and you have to jump in between words at the right time",
"Imagine an endless survival horror game where you gain coins to spend on creative scares when sneaking into your friend's game",
"My first mobile game will be free but if you pay a little then the NPC's will be extra nice and complement you more while playing.",
"Do you know what I'm fed up with? numbers in games. Don't show me how I'm doing with a number, show me with a smile or a tear.",
"You are a postman with x ray eyes. Do you post that nasty letter? Do you add extra money in that little boy's birthday card?",
"Game in which you must comfort children on a plane who are afraid of flying, game mechanic is similar to spinning plates.",
"The thing about Journey is that the person following you could POTENTIALLY be a family member who passed away. You just don't know.",
"Try to imagine a game in which you have an imaginary friend who doesn't believe you are real, you must convince them that you are.",
"Make a film about a horse, you get awards. Make a game about a horse, you get laughed at",
"3D adventure game where you have amnesia and wake up in a gigantic museum where every room is devoted to a year of your life",
"I designed a point and click adventure many years ago where you had to gain the trust of the pointer so it didn't lie to you",
"What if your friend posted a article on facebook about a serial killer, then that same killer appears in your game world?",
"In the future all games will share the same game over screen that you can customize and share with your friends",
"Imagine if your player avatar feared you? became anxious if you press the buttons too hard and fast etc?",
"What if you could plant seeds that grow into cover systems?",
"You play a father whose family dog has gone missing. You die looking for it and return home in the body of the missing dog.",
"Imagine carrying a radioactive baby in a pitch black environment, your baby would act as a torch. Rocking the baby intensifies the glow etc",
"Imagine if you had to secretly support your family via complex ventilation passages in your large industrial home?",
"In Fable 4 when you wait for the next area to load you can play darts on the new tablet that comes with the new xbox.",
"Imagine if paying bills were to be incorporated into an online videogame",
"Imagine a game in which you have to join protests to make changes to the rules within the game's world.",
"What if bullet time existed during moments such as your child dropping an ice cream, you have to leap and stop it spoiling your nice carpet?",
"Romantic parkour game in which you and the love of your life must hold hands and jump around a city evading death and injury",
"What if your son was the sun? If he sleeps, the sun vanishes. If he cries then woodlands set on fire etc",
"Game in which you control a waterfall and must travel the world hiding outdoor passages from adventurers.",
"You play a hole, you must move around an environment making certain elements fall into correct targets at the right time.",
"Imagine a co-op game where if your partner dies you have to spend 30minutes digging a hole to bury them before you can continue.",
"Imagine if you are shot in the chest and end up in hospital. Then the enemy who shot you visits with flowers.",
"What if your tummy rumbling created earthquakes? In a world where food is rare.",
"You are a small girl flying a talking kite. The kite seems to know about a upcoming major terrorist attack and floats towards clues.",
"Game where it's Xmas everyday and you can use your presents every night to progress further into a reoccurring dream.",
"Turn based 1 on 1 fighting game. Have to level up individual bones and set which order the joints are moved and rotated to create attacks",
"What if NPC's could load and save your game? You have to keep on their side otherwise they won't save your game, load old saves etc",
"New MW : You battle in huge Earth damaging wars but between missions you play as 'The Big Bang' at the start of time creating the planet.",
"Currently looking for intern programmers. NO ARTISTS please, you MAY think you know game art but trust me, your school failed you.",
"What if ghosts had dreams?",
"What if your special power was being able to fix broken smoke alarms from anywhere in the world?",
"Imagine if in new Guitar Hero you play as a busker, you witness your city evolve as your music changes the decisions of people around you",
"How about a game where you get to be a mother-in-law who bullies your son’s young wife? the aim is to have her thrown out within X months",
"New Fable Journey feature, you can read bedtime stories to goblin enemies while cradling them so they fall asleep",
"What if your 99 year old grandfather was a key? Would you force him to travel across the world just to open a secret door?",
"What if you played a game where the enemies had their children chained to them?",
"You have to bake your enemies correctly before feeding them to your master. The oven? Only accessible during the 'game over' screen",
"Imagine controlling a tear, similar to flower but instead of fields you navigate a naked body.",
"You are a bin, by day people are throwing litter in you but by night you use that litter to highlight issues in the city through modern art",
"Why is it that all puzzles are environment based? What if YOU were the puzzle? You have to adapt yourself so the environment can pass YOU?",
"You play a babysitter, you turn up and the baby is made of cardboard. Would you stay? I want games to start asking more ethical questions",
"You play a ghost in a doctor's waiting room who only children can see. You must inspire them to make the best Lego/duplex constructions?",
"You play a celebrity serial killer whose cult following exchanges ammunition/weapons for autographs?",
"You control a mystical rabbit at a bus stop during Winter. You must find as many creative ways as possible to make people miss their buses.",
"Back at last. Thanks for all the support and also thanks to whoever reported me for all the extra publicity.",
"Fun fact of the day, Edge magazine gave the same score to Fable2 as Skyrim",
"Killstreaks = X seconds of battery power. After every boss you get an extension cable, similar to hearts in Zelda.",
"What if the more XP you gained, the longer your gun extension cable grows? What if you had sissors to cut enemie's cables? True potential",
"What if you lived in a world where all guns are required to be plugged into wall sockets? Now THAT would be a tactical shooter wouldn't it?",
"Imagine walking past a mirror in a game that reflects the same surrounding area but from somebody else's game?",
"#DisneylandAdventures is frustrating, love being able to hug Mickey Mouse etc but I just want to get to know the person INSIDE the costume",
"Why do games still have maps? What if instead of moving around the world the world moved around YOU?",
"4 player online co-op where one person is the hero who can only see friend's kinect skeletons which they motion to guide the hero through",
"What if you rode a horse that knew the solution to every puzzle? Could you still ride the horse knowing that you can't communicate with it?",
"I want to make a FPS with school children and water pistols/waterbombs/sprinklers etc in a town where the water has been contaminated",
"I would share my xmas based game ideas but people would moan about it being too early",
"Imagine if enemies had tatoo passwords for doors/upgrades? You have to get close to see, harder enemies have smaller more discreet tatoos",
"A game where if you touch the floor you die. The only way to progress is to kill enemies and use their bodies as platforms.",
"Idea for a game. Painting your memories onto the environment, not sure how it works yet but the idea is quite beautiful.",
"Why does your inventory always reset every sequel? Imagine picking up a key in Fable 4 and using it on a door in Fable 7?",
"Game where you have to secretly make people fight each other and then afterwards use their bodies to make artwork that enriches NPC's lives.",
"Game in which you can use your power meter as a bridge, to make bridge reach fit bigger gaps you need to build up your power meter",
"Kinect sales have passed 10 million! and yet the first game to use it properly doesn't come out until next year",
"Imagine being able to launch a missile in Battlefield and have it hit your online friend's car in say Burnout Paradise? This is the future",
"You are a Pigeon who must go around the city trying to persuade business men not to jump off buildings by retrieving items from their home.",
"A game in which you and your father's face is a portal. You're on Earth, he is in Space. You must pass each other items to get back together",
"So after a meeting we've decided Fable Journey is indeed to be on rails BUT you can buy a DLC code that will let you go off those rails",
"Imagine an iphone game where part of the game is to leave it outside of a 500m radius of your home for 24 hours to proceed?",
"Imagine if you went home inbetween missions to look after your new born baby? Would be a nice contrast, better than bowling at least #GTA5",
"Uncharted, it's just all invisible triggers that create little events. What if there was an item that allowed you to SEE the triggers?",
"When you are about to die you must make your inventory a seed & plant it. Then die, go to the spot and wait for your inventory to grow back.",
"You are a detective solving a vital case but every time you talk to someone the Earth shakes and the environment around you falls apart?",
"You awake in a 88 floor skyscraper all alone. Every floor is haunted by one of 88 innocent people you killed during an illegal war.",
"Edge magazine has given Zelda a 10? Even EDGE don't care about refreshing and innovative games anymore. Very sad day for gaming.",
"I'm not allowed to tell you we're working on Fable:NextGen otherwise you won't bother buying Fable:Journey",
"Had to get rid of that last tweet. Please don't remember it, thanks",
"How about GearsOfWar4? You have to adjust to a post war world and open up emotionally to your estranged daughter? maybe THEN I'd play GOW",
"Imagine a constant rumble in a pad throughout the game,your heartbeat. Then at the end, you die and it just stops. Physical emotion.",
"How about something completely new? A game where you have to pay tribute to someone, collect everything about them and create a museum?",
"Actually, what if your MP3 music player's battery life was your actual life? #danceFPS",
"You regain health by dancing, which you can only do where music is playing. So you need to find musicians or maybe find a rave #danceFPS",
"Working on a concept for the world's first dancing FPS game, it's a mix between Moonwalker, Dance Central and TimeSplitters.",
"In Fable Journey, if you annoy a certain person they will show you a part of the ending cut scene from Fable4.",
"Imagine a world where people don't talk, physical words are hidden underground. You must travel the world hunting 'I', 'love' and 'you.",
"EA just closed down Bright Light here in Guildford.Thoughts go out to you all (apart from the guy who thought of making HPotter a GOW clone)",
"Imagine playing the only coin in the world and you're being used to decide on outcomes for all global debates.",
"Imagine if when you kill someone their death animation loops and 'burns' into your screen so you have to watch it for the rest of the game?",
"'Wipeout Wipeout', inbetween racing ships you get out an go through a wacky obstacle course. It's cool, New NeedForSpeed is doing it so...",
"A game where you have to kill yourself is so amateur and indy. My idea is basically you jump off bridge, floor turns into water and so on.",
"In #believe There is a room with 10,000 Milos. Which one is YOUR Milo? Can you tell? If not, I've failed. YOUR Milo will be unique to YOU.",
"Game in which you only control the angle of your character. 1 day = 1 step forward. You can buy/gift extra steps to friends.",
"In the next Fable, you will finally discover the backstory of the breadcrumbs.",
"Imagine a game with 1 goal which is to kill yourself. Now imagine that the environment constantly adapts to stop you. Excited?",
"Boss that also has a ghost. Must play spot the difference to find weak spots. Ghost only has 7 eyes? shoot that 8th eye on the boss etc",
"Racing game where you only have 2 speeds. 0MPH and 10,000 MPH. Did you just run over a little child? who knows? how does that make you feel?",
"Games on phones is wrong. If you cry, your tears will fall on the screen and mess up the image at a crucial moment. It's just wrong.",
"I do respect #stevejobs but he did sort of destroy our industry. More likely to make AngryChickens now instead of Fable 4, thanks Steve.",
"You play a boy who has a desire to educate his neighbourhood by providing them newspapers while riding a bicycle #retrodeux",
"By the way, this account is for waking up the games industry, not wishing your friend well in a charity bungee jump. NO REQUESTS PLEASE.",
"You are a frog who must cross a busy road. Twist is that traffic doesn't move smoothly, it teleports 1 step ahead continuously #retrodeux",
"My next game is going to explore the following question 'Would you give birth to a child if they were invisible?'",
"Let me tell you that gaming isn't about winning, gaming is about believing. What if games rewarded you for believing rather than winning?",
"What if everyone in the game had text constantly around them expressing their feelings? Now, imagine in this game you can CLIMB text?",
"You are a creature who can only eat bullets for survival. You must try and get people to shoot you, then go back later and eat the bullets",
"You know in cut scenes when it says '3 months later...'? What if the game ACTUALLY locked your save file for 3 months?",
"Imagine if people's emotions created gas clouds in the air which could then be inhaled, mixed or blown into other people's directions?",
"I want to make a game where you see a tree, think 'Lets use that to get to space' and you just can. Why does a tree HAVE to be just a tree?",
"Gears3. NO! Emotion in a game should not be hitting a hidden trigger that activates a sad movie. Hello Devs? Games are INTERACTIVE you know?",
"I want to make a game next year, that will be better than a game from 2030. That's just how I work...",
"For those buying Gears, hope you can sleep knowing you are part of the reason why Microsoft say yes to marines but no to little boys with ai",
"You control an entertainment unit in a large family home. You choose their games, music and films. All of which influence their future",
"Played cut the rope earlier and thought about making a game called cut the umbilical cord. I just don't care about giving candy to a frog",
"Would love to make a corridor shooter but where all walls are invisible. Constantly worrying if that enemy has open space to aim at you.",
"Also what if killing enemies makes them fall to the floor and point towards the exit? That's the only way to find your way out.",
"What if every bullet you fired hits the floor & spends 10 minutes evolving into a fast paced creature that will chase you down for revenge?",
"Can you imagine, just imagine a game where the enemies are actually able to use cheat codes?",
"If there was a villian halfway through a game who showed you the game's end cinematic would that be annoying or innovative?",
"A survival horror game where the enemies can only be seen in mirrors? Could add more depth by having dirty mirrors that need to be cleaned?",
"Surely we can reinvent FPS?  Imagine a FPS where your eyes are on the back of your head?",
"What if Flower 2 was set just after WorldWar2? You progress by touching dead bodies littered over battlefields, restoring the land.",
"Your child is made of lego, you have to detatch bricks to make bridges etc You need to keep adding bricks to stop him getting depressed.",
"sorry for the rant, back to Fable:Journey. Been recently asking myself 'what if a horse was AWARE that noises he emits are merely sfx?'",
"World is being taken over by demons, you play as a human disguised as the demon psychologist of the demon leader.",
"That bit in Fable Journey we showed you at E3 wasn't all there was to the game. It also has a bit where you throw hoops onto sticks.",
"Imagine a game where 3 pauses and it's game over. The game plays door bells, ringtones etc trying to make you accidently pause the game",
"The team currently working on #cooptopus just wanted it to be a retro side scrolling shooter, down to old me again to inject some emotion :(",
"Imagine being able to suck polygons out of enemies. initially they look next gen but you can drain them to look like they are from 1995.",
"Just tried to move a character with my tongue on the ipad, it works! Will think about this overnight and get back to you tomorrow #itongue",
"Imagine a fishing game where rivers are other different dimensions in time. You can reel in a old toy from your childhood for example",
"Adventure game where you need to follow a twitter account that provides door codes every day so you can progress further into the game",
"A game where you are in a large open world full of toxic poison, everyone wears gas masks and have to use puppets for communication",
"Was taking off the wife's dress last night and I said 'L1, R1, L1, R1' , she didn't get the reference even though I made her play Heavy Rain",
"The angle of the bullet's direction changes depending on the % that you love your cat after 3 hours. That's where I'm going with this.",
"You have 1 bullet. Once fired it enters slow motion, can take hours to reach it's target. Things you do from then on affect it's direction",
"You wake up one day in a fortress, your family are little plants. You must escape with all plants, watering them and keeping in sunlight etc",
"Imagine pressing jump and then you have a 3 day countdown until you jump. So you have to search for a gap within 3 days and then wait.",
"I also love the idea of playing a character who is PRETENDING to be blind, so you have to keep bumping into things to not arouse suspicion",
"Imagine being able to verbally tell a funny joke to a guard and causing him to roll over laughing allowing you past?",
"Imagine spying on a guard's face from afar and knowing which route he will take just by reading his facial expressions?",
"You can't depend on your eyes, when your imagination is out of Focus.",
"You are a child playing hide&seek, as you hide the world fast forwards. You come out, everyone has died. You must find your friend's ghosts",
"Online sidescrolling co-op 8 player game where each person controls a leg of a octopus. Each leg can attach guns which the player can fire",
"I want stories to have physics, THAT is interesting to me. A story that can blend naturally, bending organically and not be static",
"Physics takes away the control from us designers, instead of spending time on the game we spend time making sure they don't break things",
"Playing #FromDust again, it's like that awful indie Tetris game that has physics. Physics is the worst thing to happen to gaming this gen.",
"I would love to make a L.A Noire style detective game that features humans but they have no faces. They can't talk.",
"Game where you play a robot that must entertain a child but as he grows up the boy becomes a serial killer. Do you stop or help?",
"We need to stop making games that say 'I'm a videogame' and start making games that say 'What am I?' #xbox3",
"Can you imagine, projecting your game on top of somebody else's game? Creating special overlays that open up new abilities? #xbox3",
"Need to melt a ice door to get into a dungeon? why not project your game onto a fire? Excited yet? #xbox3",
"Project the game onto a old person, your weapon is a cane. Project the game onto a child your weapon is a balloon. #xbox3",
"Imagine projecting a game onto a male, your avatar is blue. Now project it onto a female and your avatar is pink. Tip of the iceberg #xbox3",
"Pressing buttons to fire a gun? fair enough. Pressing buttons to create magic? Sorry, you're past your sell by date #diablo3",
"For the first time ever,This new console will allow for organic game design. What if you could play a game before it's even designed? #xbox3",
"Microsoft wanted 'Milo' to be the #xbox3 dashboard. I asked them 'what if a dashboard was a game in itself?', never heard back from them",
"The week Microsoft scrapped Milo was the week they started to design #xbox3, that's what I truly believe.",
"What if a console was able to guess what you wanted to play and started to load it up as you walk into the house? #xbox3",
"This week, it's #xbox3 week. Yes, I know what the new xbox is. I can't give specifics, all very NDA. I can however share some recent dreams",
"Had a idea that combines the intimate moment of delivering babies with Crazy Taxi last night. Can emotional arcade style gaming work?",
"You are in a room with just a bed. When you sleep you become the bed. How does it feel to be a bed? degrading? what can you do about it?",
"The problem I had with lemmings is that they were just so disposable. Imagine if each and every lemming had a complex meaningful back story?",
"Instead of loading screens enemies should just pretend to 'pause' the game to annoy you?  It could actually be part of the game's story?",
"What if a game fell asleep if your actions were so tedious and repetitive?",
"Ask yourself this before you go to bed tonight. What if your soul was a grid that could be measured upon other entities within a game?",
"Imagine if controllers expressed emotions by changing temperature. Embrace a loved one, it gets warm. If they ignore you, it goes cold etc",
"What if you could write and place sticky notes in a virtual world and what they say become reality?",
"A game where custom music is the key to solving puzzles? Need to cure? Classical. Attack? Rock music. Fire? Song with the word fire in it.",
"Imagine a platformer where upon landing on the floor you create earthquakes destroying tribes of little people. Would you still jump?",
"What if your body is essentially a hourglass? Intense acrobatic game where you have to make sure sand is always falling and never stops",
"Your abusive step father chases you into a space rocket that accidently blasts off. It's just you, a 8 year old boy and him, alone in space.",
"You play as a grandad. You can only interact with your grandchildren by playing a saxaphone which is required to escape a dream like castle",
"Can you imagine playing a character who has a fully functional town on his body? Need to fix your leg? build and fund a hospital on it etc",
"What if a hiscore was infact a living character within the game world, what if you fell in love with them? and had hiscore children?",
"A game where you build/destroy sandcastles but then discover it's having an impact on the world. Like the movie 'WarGames' but with nature",
"I wanted that Rambo license. My idea was that Rambo is dead, you control his ghost and must locate and hug every one of his victim's ghosts",
"Imagine playing a game on the TV but the story is on the WiiU screen. Yet you have the ability to swap at any time.",
"The best game environments tell a story. What if you could play out that story while also playing the core game? At the same time.",
"What if a final boss had 10 minions that you had to interact with and your choice of interactions alter how the final boss battles you?",
"Strange how bosses still have weak spots that just suddenly appear? Imagine a long backstory that slowly uncovers and explains a weak spot?",
"Action game where before you can kill someone you must teleport to their family home back in time and spend a hour in their company.",
"What if you could steal animation frames from other NPC's animation cycles and give them to yourself or others to solve puzzles?",
"What if you could actually take part in a game with your family while you all sat around the dinner table eating your dinner?",
"You know, what if the aim of the game was to resist actually completing it? That kept me up all night yesterday.",
"You know I love the idea of a boy holding a ice cream which reresents his health. Similar to Dead Space's Isaac but more creative.",
"Imagine a game world where people can only convey their feelings through puppets. To show emotion x you need to steal someone elses puppet",
"A game where you have to bring in multiple characters to slow the game's frame rate down enabling you to pass obstacles etc?",
"Game where for every hour you sleep your child grows older by a week. Every hour they sleep you get younger by a week.",
"A game where you just go around listening to people, taking key words and transforming them into real objects to help you progress",
"What if falling through floors was a feature and not a bug? What lies below? want to risk your life to find out?",
"You are Cupid, you must find compatible partners. One arrow in each partner, connected with lasers. If any NPC touches laser, game over",
"is getting drunk while watching videos of 'From Dust' on youtube. I'm getting angry but I'll keep my mouth shut.",
"A survival horror game where you have to sing lullabies to your 2 year old to stop them from screaming/crying and giving your position away",
"Imagine interactive romantic novels for facebook, you may laugh but that's potentially the biggest new genre since the music game genre",
"Today I'm studying romantic gameplay mechanics.",
"Imagine a game where you are a clown and have to make others laugh YET if YOU laugh, kinect detects it and it's game over #poeticgaming",
"So far, us designers have been making incredible cuisine. However, problem is that we're serving it straight on a table rather than a plate",
"In the Shigeru Miyamoto classic, SMBros, why are there tortoises that throw hammers? No Reason. Sometimes, 'No reason' is just 'fun'.",
"What if there was a game that had no start or end but just a middle?",
"Imagine if you could upload your family photos into a game and they appear in pictures/posters etc all around the game world?",
"Why are bosses mostly big? What if the final boss was merely a cunning ant? As designers we need to challenge the 'rules' more often.",
"You grow from baby to old man and back to baby and this keeps looping every 10 seconds. Small gap? Time it so you can go through as a baby.",
"Playing Heavy Rain again, I want to take that scene where you hold a baby and sing a lullaby but make an entire game out of it.",
"Want to make our next game appeal to both sexes. For every kill you get a new piece of furniture to decorate your house?",
"There are 206 bones in the human body? Imagine, just imagine a 206 multiplayer game where each person controls a bone?",
"You are a bear but for some reason your oxygen comes from hugging people. Problem is that hugging people breaks their bones. #Poeticgaming",
"Imagine if Aeris as a ghost said you could be with her if you jump off this cliff, you do it and die, it's game over. How would you feel?",
"The Last Guardian ending? The catbird dies? Not if I was making it. I would have the boy wake up stroking his cat as it's giving birth.",
"What if a game was initially an experience and then slowly started to become a game?",
"What if you could attach a part from EVERY enemy in the game to yourself Katamari style? Building yourself and your powers up?",
"My Designer workshop #14 : Make a game where the player's only tool is a ruler.",
"You control a small child but your vision is from the teddy bear that the child is grasping onto during a war",
"What if everyone in the world had an explosive telephone in their body? If you could find out their number you can detonate their phone?",
"How do you get past a fearless guard? You extract the fear of a pigeon you just attacked and transfer it to the guard. Now he'll run away.",
"What if I were to tell you that today we've been exploring the idea of recyclable emotion?",
"I want to make a game in space. Not set in space, I mean actually develop a game in space. Would it make for a better game though?",
"Can you truly visualize in your mind the possibilities of a 'game over' screen that is also a character that can be interacted with?",
"What if you had the power to distort? What if you had the power to distort reflections?",
"Your loved one has turned into a snowman. Yet your body needs to be as hot as a oven on high heat to survive. What would you do?",
"What if all characters in a game had visible body clocks appear right above them? What if you had the power to adjust those clocks?",
"Just remember your horse has feelings – if you push your horse to the point of collapse you’re going to feel pretty guilty about that.",
"YOUR SOFA IS THE CONTROLLER",
"OF COURSE! we've all been shifting the sofa across the room while using kinect. What if we USED the sofa as a key part of the game?",
"You control someone who must entice as many people as possible to sit on a sofa within x amount of time. Like Crazy Taxi but without wheels.",
"Are we using the same incredible capture technology as that seen in L.A Noire for the horse? I couldn't possibly comment on that just yet :)",
"In Fable Journey you will be able hold out your hand and feed your horse apples but first you need to gain his trust by patting him 64 times",
"What if I were to tell you, that in Fable Journey you will be able to look into your horse's eyes and know if he is concerned?",
"Game where you must hold onto your mother's hand. Let go for more than X seconds and it's game over",
"You know, my dream for gaming is where in one game you'll shoot someone and then during a game of say Fifa you'll see their son crying",
"You live in a little house made of guns. You need many guns to fight invaders but you also need to keep a roof on top of your many children.",
"People were shouting at me not to put miscarriages in Theme Hospital, yet in kids movie 'UP' it's acceptable. I was ahead of my time.",
"Imagine Portal but in reverse. If you can't visualize that, don't bother trying to be a game designer.",
"What if your face was a mirror?",
"Imagine 'A Boy and his Blob' but instead of beans you force emotions on him. Give him contempt and he'll make a bridge, etc",
"You start the game with no emotion, you must find and obtain them and then use them to find more. My game would have 120 emotions.",
"Imagine playing the life of someone when from the start of a game a movie is constantly playing in the corner showing your child's life.",
"Have you ever played a racing game and wanted to play as the road rather than the cars? I know I have...",
"Imagine in my EPS, one is in a empty room with a locked door but another is in a room with a key. Overlay their vision and you can get out",
"I would create the worlds first EPS. Eight peoples vision overlayed on top of each other to create Eight Person Perspective.",
"FPS never really evolved. If I did a FPS I wouldn't make it first person view for starters. I'd break that rule straight away.",
"Take away the atmosphere, take away the magic, take away the stylized flashy graphics and Bioshock Infinite is basically just Doom",
"You have to battle your way out of a battlezone while also maneuvering a pram with a baby, you can attach armour to pram and use as cover",
"War game where at the end you walk through a graveyard looking at each and every headstone of those you killed followed with 1minute silence",
"I want to use lying system from L.A and have you play as a teacher in a elementry school. Did kid A really put woodlice in kid B's yogurt?",
"How about this, listen, a game where you can control if it's in HD or SD and both play a vital part in solving puzzles?",
"You are a scarecrow in a world with just 1 bird",
"Imagine an action game where upon killing each enemy you see a 1 minute unique cutscene flashing through their entire life",
"What if your body was a washing machine and you had to wash your enemies before you can kill them?",
"I'm the British Miyamoto. I refuse to call it Fable 4, Fable Journey is my Super Mario World.  Who needs SMB4?",
"You play as a small boy with a remote control helicoptor that is alive and your friend, then you discover a nuclear missle inside it",
"Other things I would like to play as are dust, regret as a character, a microwave, carpet, lung, statue, bullet, television and a nose."
];
